project:
  type: website
  render:
    - "*.qmd"
    - "!slides/" # don't knit slides when website is updated
    - "!files/"
  resources:
    - "files/"
    - "slides/"
    - "images/"

website:
  title: "ECON 326 — Industrial Organization"
  favicon: "images/io_hex.png"
  open-graph: true
  twitter-card: true
  image: "images/io_hex.png"
  navbar:
    pinned: true
    search: true
    logo: "images/io_hex.png"
    right:
      - syllabus.qmd
      - schedule.qmd
      - text: Content
        href: content/index.qmd
      - text: Assignments
        href: assignments/index.qmd
      - text: Resources
        href: resources/index.qmd
  sidebar:
    - title: "Content"
      style: "docked"
      search: false
      contents:
        - section: "Overview"
          contents: 
            - content/index.qmd
        - section: "I. Models of Markets"
          contents: 
            - text: "1.1 — Introduction to I.O."
              href: content/1.1-content.qmd
            - text: "1.2 — Technology and Cost"
              href: content/1.2-content.qmd
            - text: "1.3 — Perfect Competition I"
              href: content/1.3-content.qmd
            - text: "1.4 — Perfect Competition II"
              href: content/1.4-content.qmd
            - text: "1.5 — Monopoly I"
              href: content/1.5-content.qmd
            - text: "1.6 — Monopoly II"
              href: content/1.6-content.qmd
            - text: "1.7 — Pricing Strategies"
              href: content/1.7-content.qmd
            - text: "1.8 — Factor Markets"
              href: content/1.8-content.qmd
        - section: "II. Oligopoly & Static Game Theory"
          contents: 
            - text: "1.1 — Imperfect Competition & Collusion"
              href: content/2.1-content.qmd
            - text: "2.2 — Cournot Competition"
              href: content/2.2-content.qmd
            - text: "2.3 — Bertrand Competition"
              href: content/2.3-content.qmd
        - section: "III. Strategic Behavior & Dynamic Games"
          contents: 
            - text: "3.1 — Dynamic Games & Collusion"
              href: content/3.1-content.qmd
            - text: "3.2 — Stackelberg Competition"
              href: content/3.2-content.qmd
            - text: "3.3 — Entry Deterrence and Commitment"
              href: content/3.3-content.qmd
        - section: "IV. Theory of the Firm & Economic Organization"
          contents:
            - text: "4.1 — Why Are There Firms?"
              href: content/4.1-content.qmd
    - title: "Assignments"
      style: "docked"
      search: false
      contents:
        - section: "Assignments"
          contents:
            - assignments/index.qmd
        - section: "Problem Sets"
          contents:
            - text: "Instructions"
              href: assignments/problem-sets.qmd
            - text: "Problem Set 1"
              href: assignments/01-problem-set.qmd
            - text: "Problem Set 2"
              href: assignments/02-problem-set.qmd
        - section: "Exams"
          contents:
            - text: "Midterm Exam"
              href: assignments/midterm.qmd

    - title: "Resources"
      style: "docked"
      search: true
      contents:
        - text: "Overview"
          href: resources/index.qmd
        - section: "Appendices"
          contents:
        - section: "Computing Guides"
          contents:
          - href: resources/pdfs.qmd
            text: "How to Make a PDF"
        - section: "Advice"
          contents:
          - href: resources/tips.qmd
            text: "Tips for Success"
        - text: "Quotes About Economics"
          href: resources/quotes.qmd

  page-footer:
    left: |
      Content {{< fa brands creative-commons >}} {{< var course.copyright_year >}} by [{{< var instructor.name_no_title >}}]({{< var instructor.url >}}) <br>
      All content licensed under a {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-nc >}}
      [Creative Commons Attribution-NonCommercial 4.0 International license (CC BY-NC 4.0)](https://creativecommons.org/licenses/by-nc/4.0/)
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
      [View the source at {{< fa brands github >}} GitHub]({{< var course.github >}})

format:
  html:
    theme:
      - cosmo
      - html/custom.scss
    css: styles.css
    toc: true

editor: visual

