---
title: "Industry Report"
execute: 
  freeze: auto
---

```{r message=FALSE, warning=FALSE, include=FALSE}
library(tidyverse)
```

::: {.callout-warning appearance="minimal"}
Paper is due by the last day of the semester, May 8; Presentations will be the last meeting day (or two) of this course
:::

# Overview 

Over the semester, you will write and briefly present a report on an industry that you choose that describes the market for the product: the geographic, vertical, and horizontal boundaries, the nature of competition, costs, demand, and regulatory environment. 

Please **email me** with an industry you would like to choose. I will remove industries from this list in the order that I receive emails claiming them. You may decide to change your industry at any time, at which point, I will re-release the industry into the pool for others to select, and update the list below:


### Claimed Industries

 You can choose any U.S. industry **except** for the following that have been claimed:

- Beer
- Wine

**Last Update: March 20, 2023**

# Assignment

I want you to compile information and some statistics on a chosen industry (described below) and write a report (anticipate about 10 $\pm$ 5 pages). Note that some industries may not have data available on all statistics (and be sure to note if none are available). On the last week of class, each student will have 5 minutes to present their industry. I expect each of you to have slides to describe your industry.

Your report (and summarized in your presentation) should cover: 

### Industry Definition

Define and describe your chosen industry. Discuss the market in terms of horizontal, vertical, and geographic boundaries. Discuss upstream and downstream industries if applicable. Choose the measure(s) of output that you believe to be the most descriptive of your industry and explain your reasoning.

### History of the Industry

Write a brief history of the industry. Describe how and when it started. Discuss how the industry has evolved over time and the direction in which it appears to be heading. What are the major challenges/opportunities going forward?

### Demand Characteristics

Is the demand for the produce relatively elastic or inelastic? Are these items often high budget or low budget for customers/consumers? Are they necessities or luxuries? What are significant substitutes for the goods/services produced by the industry? Are there complements? Is demand growing or declining? Do consumers have similar preferences or do consumers differ significantly in their preferences?

Note for these questions/section you will probably not find much data or evidence, so you will have to rely on your economic intuition and knowledge of the industry.

### Firms & Concentration

To the extent you can find data: identify the major firms in the industry and determine their relative market shares. How concentrated is this industry? How much market power do firms enjoy? Choose the measure(s) that you believe most descriptive given your industry (concentration ratios, HHI, Lerner index, etc.), and explain your choice. Has the industry always been this concentrated, or has it concentration changed over time? Why? Have the top firms always been the same, or have the dominant firms changed over time?

### Cost Structure

Discuss the technology and cost structure of the industry. What are the significant fixed and variable costs? Are variable costs high, low, constant? Are fixed costs much higher than variable costs? Are there sunk costs? Are there economies of scale? Economies of scope? 

You will also not be able to get data or direct evidence (e.g. cost functions) for the firms. Again, consider this qualitatively, given your economic intuition and knowledge of the industry.

### Competition & Firm Conduct

How do firms compete in this industry? On price? Quantity? Are there leaders/dominant firms? Do firms innovate much? Are there lawsuits?

Assess the possibility of collusion in this industry. Consider the characteristics we discussed that might facilitate/impede collusive efforts.

How contestable is the market? How easy/difficult is it for potential entrants to enter? Who might these entrants be? What, if anything, do incumbent firms do to deter entry? Are there barriers to entry?  

### Regulation

Who is(are) the major regulator(s) of this industry? Discuss the regulatory history of this industry (you can blend this in with the history of the industry above) and why there were any significant changes. What were/are the major types of regulation and rationales for them (e.g. price controls, entry regulations, quality standards, etc). Have there been (or are there currently) major (attempted) mergers (and were they approved or denied by regulators, and why)? 

# Good Data Sources

- [Statista](https://statista.com)
- [U.S. Census (Business Economy)](https://www.census.gov/topics/business-economy.html)
- [Economic Census](https://www.census.gov/programs-surveys/economic-census.html)
- [U.S. Census (Current Industrial Reports)](https://www.census.gov/programs-surveys/current-industrial-reports.html)
- [data.gov](https://catalog.data.gov/dataset)
- [Federal Trade Commission: Competition Enforcement Database](https://www.ftc.gov/competition-enforcement-database)
- [Federal Trade Commission: Annual Competition Reports](https://www.ftc.gov/policy/reports/annual-competition-reports)
- [Federal Reserve Economic Database](https://fred.stlouisfed.org/)
- [IPUMS](https://www.ipums.org/)
- Search the website of an industry's regulator(s), e.g. FAA (airlines), SEC/OCC/Federal Reserve (for finance/banking), DOE/FERC (for energy), FDA/USDA (for pharmaceuticals, agriculture, food, beverages), etc.
- Trade associations and other industry groups  often aggregate industry data and provide regular reports on their industry (e.g. RIAA for music, MPAA for movies, Publishers' Weekly, etc.)
- It's possible something from my [list of data sources](https://metricsf22.classes.ryansafner.com/resources/data.html) for my econometrics course may help you

Government agencies and business information providers use [NAICS](https://www.census.gov/naics/) to organize industry information. You can search several business databases by NAICS and/or SIC codes for industry information.

# Suggested Industries

- Accounting firms
- Agricultural Businesses (e.g. Cargill, ADM, etc)
- Aircraft Manufacturers
- Airlines (Commercial)
- Apparel: womens, men
- Athletic shoes
- Athleisure wear
- Automobile manufacturers
- Baby formula
- Banking
- Beverages (e.g. beer, soft drinks, cofee)
- Cell phone service
- Cigarettes
- Commercial Banking
- Computers (software; hardware)
- Consulting (management)
- Consumer electronics (e.g. TVs)
- Cruise lines
- Diapers
- Energy (natural gas, electricity)
- Food (fast food; breakfast cereals; etc)
- Food Trucks
- Furniture
- Gas stations
- Greeting Cards
- Health care (nursing homes, hospitals, health insurance, pharmaceuticals)
- Hotels
- Insurance (property, life, etc.)
- Mattresses
- Movies
- Music
- Paper
- Pet food
- Plastics
- Publishing
- Restaurants
- Retail (clothing e.g. Target, Walmart; electronics e.g. Best Buy, etc.)
- Shipping (cargo ships, trucking, air cargo)
- Sports (professional baseball, football, basketball, etc)
- Steel
- Telecommunications (telephone, cable & satellite, radio, broadband internet)
- Tires
- Toys
- Video games
- Water utilities
- Wine
